// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: example/example.proto

package example

import options "github.com/infobloxopen/protoc-gen-atlas-query-perm/options"
import query "github.com/infobloxopen/atlas-app-toolkit/query"

// Reference imports to suppress errors if they are not otherwise used.

var exampleMessagesRequiredValidation = map[string]map[string]options.FilteringOption{
	"User": {
		"first_name":  options.FilteringOption{DisableSorting: false, Deny: []string{"EQ", "GT", "GE", "LT", "LE"}},
		"middle_name": options.FilteringOption{DisableSorting: true, Deny: []string{""}},
		"last_name":   options.FilteringOption{DisableSorting: false, Deny: []string{"LT", "LE", "MATCH", "GT", "GE"}},
		"age":         options.FilteringOption{DisableSorting: false, Deny: []string{"EQ", "GT", "GE", "LT", "LE"}},
		"height":      options.FilteringOption{DisableSorting: false, Deny: []string{"EQ", "GT", "LT", "LE"}},
		"weight":      options.FilteringOption{DisableSorting: false, Deny: []string{"LE"}},
		"OnVacation":  options.FilteringOption{DisableSorting: true, Deny: []string{""}},
	},
}
var exampleMethodsRequiredFilteringValidation = map[string]string{
	"/example.TestService/List": "User",
}
var exampleMethodsRequiredPagingValidation = map[string]string{
	"/example.TestService/List": "User",
	"/example.TestService/Read": "User",
}

func Validate(f *query.Filtering, p *query.Sorting, methodName string) error {
	perm, ok := exampleMethodsRequiredFilteringValidation[methodName]
	if !ok {
		return nil
	}
	res := options.ValidateFilteringPermissions(f, perm, exampleMessagesRequiredValidation)
	if res != nil {
		return res
	}
	perm, ok = exampleMethodsRequiredPagingValidation[methodName]
	if !ok {
		return nil
	}
	res = options.ValidateSortingPermissions(p, perm, exampleMessagesRequiredValidation)
	if res != nil {
		return res
	}
	return nil
}
