// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: options/query_validate.proto

package options // import "github.com/infobloxopen/protoc-gen-atlas-query-validate/options"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import descriptor "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type QueryValidate_FilterOperator int32

const (
	QueryValidate_EQ    QueryValidate_FilterOperator = 0
	QueryValidate_MATCH QueryValidate_FilterOperator = 1
	QueryValidate_GT    QueryValidate_FilterOperator = 2
	QueryValidate_GE    QueryValidate_FilterOperator = 3
	QueryValidate_LT    QueryValidate_FilterOperator = 4
	QueryValidate_LE    QueryValidate_FilterOperator = 5
	QueryValidate_ALL   QueryValidate_FilterOperator = 6
)

var QueryValidate_FilterOperator_name = map[int32]string{
	0: "EQ",
	1: "MATCH",
	2: "GT",
	3: "GE",
	4: "LT",
	5: "LE",
	6: "ALL",
}
var QueryValidate_FilterOperator_value = map[string]int32{
	"EQ":    0,
	"MATCH": 1,
	"GT":    2,
	"GE":    3,
	"LT":    4,
	"LE":    5,
	"ALL":   6,
}

func (x QueryValidate_FilterOperator) Enum() *QueryValidate_FilterOperator {
	p := new(QueryValidate_FilterOperator)
	*p = x
	return p
}
func (x QueryValidate_FilterOperator) String() string {
	return proto.EnumName(QueryValidate_FilterOperator_name, int32(x))
}
func (x *QueryValidate_FilterOperator) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(QueryValidate_FilterOperator_value, data, "QueryValidate_FilterOperator")
	if err != nil {
		return err
	}
	*x = QueryValidate_FilterOperator(value)
	return nil
}
func (QueryValidate_FilterOperator) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_query_validate_bbf84f384cccf205, []int{0, 0}
}

type QueryValidate_ValueType int32

const (
	QueryValidate_DEFAULT      QueryValidate_ValueType = 0
	QueryValidate_STRING       QueryValidate_ValueType = 1
	QueryValidate_NUMBER       QueryValidate_ValueType = 2
	QueryValidate_STRING_ARRAY QueryValidate_ValueType = 3
	QueryValidate_NUMBER_ARRAY QueryValidate_ValueType = 4
)

var QueryValidate_ValueType_name = map[int32]string{
	0: "DEFAULT",
	1: "STRING",
	2: "NUMBER",
	3: "STRING_ARRAY",
	4: "NUMBER_ARRAY",
}
var QueryValidate_ValueType_value = map[string]int32{
	"DEFAULT":      0,
	"STRING":       1,
	"NUMBER":       2,
	"STRING_ARRAY": 3,
	"NUMBER_ARRAY": 4,
}

func (x QueryValidate_ValueType) Enum() *QueryValidate_ValueType {
	p := new(QueryValidate_ValueType)
	*p = x
	return p
}
func (x QueryValidate_ValueType) String() string {
	return proto.EnumName(QueryValidate_ValueType_name, int32(x))
}
func (x *QueryValidate_ValueType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(QueryValidate_ValueType_value, data, "QueryValidate_ValueType")
	if err != nil {
		return err
	}
	*x = QueryValidate_ValueType(value)
	return nil
}
func (QueryValidate_ValueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_query_validate_bbf84f384cccf205, []int{0, 1}
}

type QueryValidate struct {
	Filtering            *QueryValidate_Filtering `protobuf:"bytes,1,opt,name=filtering" json:"filtering,omitempty"`
	Sorting              *QueryValidate_Sorting   `protobuf:"bytes,2,opt,name=sorting" json:"sorting,omitempty"`
	ValueType            *QueryValidate_ValueType `protobuf:"varint,3,opt,name=value_type,json=valueType,enum=atlas.query.QueryValidate_ValueType" json:"value_type,omitempty"`
	EnableNestedFields   *bool                    `protobuf:"varint,4,opt,name=enable_nested_fields,json=enableNestedFields" json:"enable_nested_fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *QueryValidate) Reset()         { *m = QueryValidate{} }
func (m *QueryValidate) String() string { return proto.CompactTextString(m) }
func (*QueryValidate) ProtoMessage()    {}
func (*QueryValidate) Descriptor() ([]byte, []int) {
	return fileDescriptor_query_validate_bbf84f384cccf205, []int{0}
}
func (m *QueryValidate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryValidate.Unmarshal(m, b)
}
func (m *QueryValidate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryValidate.Marshal(b, m, deterministic)
}
func (dst *QueryValidate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidate.Merge(dst, src)
}
func (m *QueryValidate) XXX_Size() int {
	return xxx_messageInfo_QueryValidate.Size(m)
}
func (m *QueryValidate) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidate.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidate proto.InternalMessageInfo

func (m *QueryValidate) GetFiltering() *QueryValidate_Filtering {
	if m != nil {
		return m.Filtering
	}
	return nil
}

func (m *QueryValidate) GetSorting() *QueryValidate_Sorting {
	if m != nil {
		return m.Sorting
	}
	return nil
}

func (m *QueryValidate) GetValueType() QueryValidate_ValueType {
	if m != nil && m.ValueType != nil {
		return *m.ValueType
	}
	return QueryValidate_DEFAULT
}

func (m *QueryValidate) GetEnableNestedFields() bool {
	if m != nil && m.EnableNestedFields != nil {
		return *m.EnableNestedFields
	}
	return false
}

type QueryValidate_Filtering struct {
	Allow                []QueryValidate_FilterOperator `protobuf:"varint,1,rep,name=allow,enum=atlas.query.QueryValidate_FilterOperator" json:"allow,omitempty"`
	Deny                 []QueryValidate_FilterOperator `protobuf:"varint,2,rep,name=deny,enum=atlas.query.QueryValidate_FilterOperator" json:"deny,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *QueryValidate_Filtering) Reset()         { *m = QueryValidate_Filtering{} }
func (m *QueryValidate_Filtering) String() string { return proto.CompactTextString(m) }
func (*QueryValidate_Filtering) ProtoMessage()    {}
func (*QueryValidate_Filtering) Descriptor() ([]byte, []int) {
	return fileDescriptor_query_validate_bbf84f384cccf205, []int{0, 0}
}
func (m *QueryValidate_Filtering) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryValidate_Filtering.Unmarshal(m, b)
}
func (m *QueryValidate_Filtering) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryValidate_Filtering.Marshal(b, m, deterministic)
}
func (dst *QueryValidate_Filtering) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidate_Filtering.Merge(dst, src)
}
func (m *QueryValidate_Filtering) XXX_Size() int {
	return xxx_messageInfo_QueryValidate_Filtering.Size(m)
}
func (m *QueryValidate_Filtering) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidate_Filtering.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidate_Filtering proto.InternalMessageInfo

func (m *QueryValidate_Filtering) GetAllow() []QueryValidate_FilterOperator {
	if m != nil {
		return m.Allow
	}
	return nil
}

func (m *QueryValidate_Filtering) GetDeny() []QueryValidate_FilterOperator {
	if m != nil {
		return m.Deny
	}
	return nil
}

type QueryValidate_Sorting struct {
	Disable              *bool    `protobuf:"varint,1,opt,name=disable" json:"disable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryValidate_Sorting) Reset()         { *m = QueryValidate_Sorting{} }
func (m *QueryValidate_Sorting) String() string { return proto.CompactTextString(m) }
func (*QueryValidate_Sorting) ProtoMessage()    {}
func (*QueryValidate_Sorting) Descriptor() ([]byte, []int) {
	return fileDescriptor_query_validate_bbf84f384cccf205, []int{0, 1}
}
func (m *QueryValidate_Sorting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryValidate_Sorting.Unmarshal(m, b)
}
func (m *QueryValidate_Sorting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryValidate_Sorting.Marshal(b, m, deterministic)
}
func (dst *QueryValidate_Sorting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidate_Sorting.Merge(dst, src)
}
func (m *QueryValidate_Sorting) XXX_Size() int {
	return xxx_messageInfo_QueryValidate_Sorting.Size(m)
}
func (m *QueryValidate_Sorting) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidate_Sorting.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidate_Sorting proto.InternalMessageInfo

func (m *QueryValidate_Sorting) GetDisable() bool {
	if m != nil && m.Disable != nil {
		return *m.Disable
	}
	return false
}

var E_Validate = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*QueryValidate)(nil),
	Field:         52121,
	Name:          "atlas.query.validate",
	Tag:           "bytes,52121,opt,name=validate",
	Filename:      "options/query_validate.proto",
}

func init() {
	proto.RegisterType((*QueryValidate)(nil), "atlas.query.QueryValidate")
	proto.RegisterType((*QueryValidate_Filtering)(nil), "atlas.query.QueryValidate.Filtering")
	proto.RegisterType((*QueryValidate_Sorting)(nil), "atlas.query.QueryValidate.Sorting")
	proto.RegisterEnum("atlas.query.QueryValidate_FilterOperator", QueryValidate_FilterOperator_name, QueryValidate_FilterOperator_value)
	proto.RegisterEnum("atlas.query.QueryValidate_ValueType", QueryValidate_ValueType_name, QueryValidate_ValueType_value)
	proto.RegisterExtension(E_Validate)
}

func init() {
	proto.RegisterFile("options/query_validate.proto", fileDescriptor_query_validate_bbf84f384cccf205)
}

var fileDescriptor_query_validate_bbf84f384cccf205 = []byte{
	// 477 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x8f, 0x93, 0x40,
	0x18, 0x5e, 0x3e, 0xb6, 0x94, 0xb7, 0xda, 0x4c, 0x26, 0x1e, 0x48, 0xa3, 0x09, 0xa9, 0x1e, 0xea,
	0xa1, 0x60, 0xf6, 0xe8, 0x47, 0x0c, 0x5d, 0x69, 0xdd, 0x84, 0xed, 0x66, 0x67, 0xd9, 0x35, 0x7a,
	0x21, 0xb4, 0x4c, 0x91, 0x64, 0x64, 0x10, 0xa6, 0xd5, 0xfe, 0x06, 0x7f, 0x80, 0xf1, 0xd7, 0xf9,
	0x57, 0x0c, 0x03, 0x54, 0xf7, 0xe0, 0x1a, 0x4f, 0xef, 0xf0, 0x3e, 0x1f, 0x19, 0x1e, 0x1e, 0xe0,
	0x21, 0x2f, 0x44, 0xc6, 0xf3, 0xca, 0xfd, 0xbc, 0xa5, 0xe5, 0x3e, 0xda, 0xc5, 0x2c, 0x4b, 0x62,
	0x41, 0x9d, 0xa2, 0xe4, 0x82, 0xe3, 0x41, 0x2c, 0x58, 0x5c, 0x39, 0x12, 0x1b, 0xd9, 0x29, 0xe7,
	0x29, 0xa3, 0xae, 0x84, 0x56, 0xdb, 0x8d, 0x9b, 0xd0, 0x6a, 0x5d, 0x66, 0x85, 0xe0, 0x65, 0x43,
	0x1f, 0xff, 0xd4, 0xe1, 0xfe, 0x65, 0xcd, 0xbd, 0x69, 0x6d, 0xf0, 0x0c, 0xcc, 0x4d, 0xc6, 0x04,
	0x2d, 0xb3, 0x3c, 0xb5, 0x14, 0x5b, 0x99, 0x0c, 0x4e, 0x9e, 0x38, 0x7f, 0x98, 0x3a, 0xb7, 0xe8,
	0xce, 0xbc, 0xe3, 0x92, 0xdf, 0x32, 0xfc, 0x12, 0x8c, 0x8a, 0x97, 0xa2, 0x76, 0x50, 0xa5, 0xc3,
	0xf8, 0x0e, 0x87, 0xab, 0x86, 0x49, 0x3a, 0x09, 0x3e, 0x05, 0xd8, 0xc5, 0x6c, 0x4b, 0x23, 0xb1,
	0x2f, 0xa8, 0xa5, 0xd9, 0xca, 0x64, 0x78, 0xe7, 0x15, 0x6e, 0x6a, 0x72, 0xb8, 0x2f, 0x28, 0x31,
	0x77, 0xdd, 0x11, 0x3f, 0x83, 0x07, 0x34, 0x8f, 0x57, 0x8c, 0x46, 0x39, 0xad, 0x04, 0x4d, 0xa2,
	0x4d, 0x46, 0x59, 0x52, 0x59, 0xba, 0xad, 0x4c, 0xfa, 0x04, 0x37, 0xd8, 0x52, 0x42, 0x73, 0x89,
	0x8c, 0xbe, 0x29, 0x60, 0x1e, 0xde, 0x06, 0xbf, 0x86, 0xe3, 0x98, 0x31, 0xfe, 0xc5, 0x52, 0x6c,
	0x6d, 0x32, 0x3c, 0x79, 0xfa, 0xcf, 0x08, 0x2e, 0x0a, 0x5a, 0xc6, 0x82, 0x97, 0xa4, 0xd1, 0xe1,
	0x57, 0xa0, 0x27, 0x34, 0xdf, 0x5b, 0xea, 0xff, 0xea, 0xa5, 0x6c, 0xf4, 0x18, 0x8c, 0x36, 0x18,
	0x6c, 0x81, 0x91, 0x64, 0x55, 0x7d, 0x5f, 0xf9, 0x3d, 0xfa, 0xa4, 0x7b, 0x1c, 0x07, 0x30, 0xbc,
	0x2d, 0xc6, 0x3d, 0x50, 0xfd, 0x4b, 0x74, 0x84, 0x4d, 0x38, 0x3e, 0xf7, 0xc2, 0xd3, 0xb7, 0x48,
	0xa9, 0x57, 0x8b, 0x10, 0xa9, 0x72, 0xfa, 0x48, 0xab, 0x67, 0x10, 0x22, 0x5d, 0x4e, 0x1f, 0x1d,
	0x63, 0x03, 0x34, 0x2f, 0x08, 0x50, 0x6f, 0x1c, 0x82, 0x79, 0x88, 0x12, 0x0f, 0xc0, 0x78, 0xe3,
	0xcf, 0xbd, 0xeb, 0x20, 0x44, 0x47, 0x18, 0xa0, 0x77, 0x15, 0x92, 0xb3, 0xe5, 0x02, 0x29, 0xf5,
	0x79, 0x79, 0x7d, 0x3e, 0xf3, 0x09, 0x52, 0x31, 0x82, 0x7b, 0xcd, 0x3e, 0xf2, 0x08, 0xf1, 0xde,
	0x23, 0xad, 0xde, 0x34, 0x68, 0xbb, 0xd1, 0x9f, 0xbf, 0x83, 0x7e, 0x57, 0x51, 0xfc, 0xc8, 0x69,
	0x0a, 0xe9, 0x74, 0x85, 0x74, 0x64, 0xf6, 0x17, 0x4d, 0xa1, 0xad, 0x1f, 0xdf, 0x35, 0xd9, 0x96,
	0xd1, 0xdf, 0xc3, 0x22, 0x07, 0xb3, 0xd9, 0xd9, 0x87, 0x45, 0x9a, 0x89, 0x8f, 0xdb, 0x95, 0xb3,
	0xe6, 0x9f, 0xdc, 0x2c, 0xdf, 0xf0, 0x15, 0xe3, 0x5f, 0x79, 0x41, 0xf3, 0xa6, 0xef, 0xeb, 0x69,
	0x4a, 0xf3, 0xa9, 0x74, 0x9a, 0x4a, 0xa7, 0x69, 0x27, 0x75, 0xdb, 0x3f, 0xe8, 0x45, 0x3b, 0x7f,
	0x05, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xba, 0x61, 0x69, 0x53, 0x03, 0x00, 0x00,
}
