// Code generated by protoc-gen-gogo.
// source: options/query_validate.proto
// DO NOT EDIT!

/*
Package options is a generated protocol buffer package.

It is generated from these files:
	options/query_validate.proto

It has these top-level messages:
	QueryValidate
	MessageQueryValidate
*/
package options

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type QueryValidate_FilterOperator int32

const (
	QueryValidate_EQ    QueryValidate_FilterOperator = 0
	QueryValidate_MATCH QueryValidate_FilterOperator = 1
	QueryValidate_GT    QueryValidate_FilterOperator = 2
	QueryValidate_GE    QueryValidate_FilterOperator = 3
	QueryValidate_LT    QueryValidate_FilterOperator = 4
	QueryValidate_LE    QueryValidate_FilterOperator = 5
	QueryValidate_ALL   QueryValidate_FilterOperator = 6
	QueryValidate_IEQ   QueryValidate_FilterOperator = 7
	QueryValidate_IN    QueryValidate_FilterOperator = 8
)

var QueryValidate_FilterOperator_name = map[int32]string{
	0: "EQ",
	1: "MATCH",
	2: "GT",
	3: "GE",
	4: "LT",
	5: "LE",
	6: "ALL",
	7: "IEQ",
	8: "IN",
}
var QueryValidate_FilterOperator_value = map[string]int32{
	"EQ":    0,
	"MATCH": 1,
	"GT":    2,
	"GE":    3,
	"LT":    4,
	"LE":    5,
	"ALL":   6,
	"IEQ":   7,
	"IN":    8,
}

func (x QueryValidate_FilterOperator) String() string {
	return proto.EnumName(QueryValidate_FilterOperator_name, int32(x))
}
func (QueryValidate_FilterOperator) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorQueryValidate, []int{0, 0}
}

type QueryValidate_ValueType int32

const (
	QueryValidate_DEFAULT QueryValidate_ValueType = 0
	QueryValidate_STRING  QueryValidate_ValueType = 1
	QueryValidate_NUMBER  QueryValidate_ValueType = 2
)

var QueryValidate_ValueType_name = map[int32]string{
	0: "DEFAULT",
	1: "STRING",
	2: "NUMBER",
}
var QueryValidate_ValueType_value = map[string]int32{
	"DEFAULT": 0,
	"STRING":  1,
	"NUMBER":  2,
}

func (x QueryValidate_ValueType) String() string {
	return proto.EnumName(QueryValidate_ValueType_name, int32(x))
}
func (QueryValidate_ValueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorQueryValidate, []int{0, 1}
}

type QueryValidate struct {
	Filtering          *QueryValidate_Filtering      `protobuf:"bytes,1,opt,name=filtering" json:"filtering,omitempty"`
	Sorting            *QueryValidate_Sorting        `protobuf:"bytes,2,opt,name=sorting" json:"sorting,omitempty"`
	FieldSelection     *QueryValidate_FieldSelection `protobuf:"bytes,3,opt,name=field_selection,json=fieldSelection" json:"field_selection,omitempty"`
	ValueType          QueryValidate_ValueType       `protobuf:"varint,4,opt,name=value_type,json=valueType,proto3,enum=atlas.query.QueryValidate_ValueType" json:"value_type,omitempty"`
	ValueTypeUrl       string                        `protobuf:"bytes,5,opt,name=value_type_url,json=valueTypeUrl,proto3" json:"value_type_url,omitempty"`
	EnableNestedFields bool                          `protobuf:"varint,6,opt,name=enable_nested_fields,json=enableNestedFields,proto3" json:"enable_nested_fields,omitempty"`
	NestedFields       []string                      `protobuf:"bytes,7,rep,name=nested_fields,json=nestedFields" json:"nested_fields,omitempty"`
}

func (m *QueryValidate) Reset()                    { *m = QueryValidate{} }
func (m *QueryValidate) String() string            { return proto.CompactTextString(m) }
func (*QueryValidate) ProtoMessage()               {}
func (*QueryValidate) Descriptor() ([]byte, []int) { return fileDescriptorQueryValidate, []int{0} }

func (m *QueryValidate) GetFiltering() *QueryValidate_Filtering {
	if m != nil {
		return m.Filtering
	}
	return nil
}

func (m *QueryValidate) GetSorting() *QueryValidate_Sorting {
	if m != nil {
		return m.Sorting
	}
	return nil
}

func (m *QueryValidate) GetFieldSelection() *QueryValidate_FieldSelection {
	if m != nil {
		return m.FieldSelection
	}
	return nil
}

func (m *QueryValidate) GetValueType() QueryValidate_ValueType {
	if m != nil {
		return m.ValueType
	}
	return QueryValidate_DEFAULT
}

func (m *QueryValidate) GetValueTypeUrl() string {
	if m != nil {
		return m.ValueTypeUrl
	}
	return ""
}

func (m *QueryValidate) GetEnableNestedFields() bool {
	if m != nil {
		return m.EnableNestedFields
	}
	return false
}

func (m *QueryValidate) GetNestedFields() []string {
	if m != nil {
		return m.NestedFields
	}
	return nil
}

type QueryValidate_Filtering struct {
	Allow []QueryValidate_FilterOperator `protobuf:"varint,1,rep,packed,name=allow,enum=atlas.query.QueryValidate_FilterOperator" json:"allow,omitempty"`
	Deny  []QueryValidate_FilterOperator `protobuf:"varint,2,rep,packed,name=deny,enum=atlas.query.QueryValidate_FilterOperator" json:"deny,omitempty"`
}

func (m *QueryValidate_Filtering) Reset()         { *m = QueryValidate_Filtering{} }
func (m *QueryValidate_Filtering) String() string { return proto.CompactTextString(m) }
func (*QueryValidate_Filtering) ProtoMessage()    {}
func (*QueryValidate_Filtering) Descriptor() ([]byte, []int) {
	return fileDescriptorQueryValidate, []int{0, 0}
}

func (m *QueryValidate_Filtering) GetAllow() []QueryValidate_FilterOperator {
	if m != nil {
		return m.Allow
	}
	return nil
}

func (m *QueryValidate_Filtering) GetDeny() []QueryValidate_FilterOperator {
	if m != nil {
		return m.Deny
	}
	return nil
}

type QueryValidate_Sorting struct {
	Disable bool `protobuf:"varint,1,opt,name=disable,proto3" json:"disable,omitempty"`
}

func (m *QueryValidate_Sorting) Reset()         { *m = QueryValidate_Sorting{} }
func (m *QueryValidate_Sorting) String() string { return proto.CompactTextString(m) }
func (*QueryValidate_Sorting) ProtoMessage()    {}
func (*QueryValidate_Sorting) Descriptor() ([]byte, []int) {
	return fileDescriptorQueryValidate, []int{0, 1}
}

func (m *QueryValidate_Sorting) GetDisable() bool {
	if m != nil {
		return m.Disable
	}
	return false
}

type QueryValidate_FieldSelection struct {
	Disable bool `protobuf:"varint,1,opt,name=disable,proto3" json:"disable,omitempty"`
}

func (m *QueryValidate_FieldSelection) Reset()         { *m = QueryValidate_FieldSelection{} }
func (m *QueryValidate_FieldSelection) String() string { return proto.CompactTextString(m) }
func (*QueryValidate_FieldSelection) ProtoMessage()    {}
func (*QueryValidate_FieldSelection) Descriptor() ([]byte, []int) {
	return fileDescriptorQueryValidate, []int{0, 2}
}

func (m *QueryValidate_FieldSelection) GetDisable() bool {
	if m != nil {
		return m.Disable
	}
	return false
}

type MessageQueryValidate struct {
	Validate []*MessageQueryValidate_QueryValidateEntry `protobuf:"bytes,1,rep,name=validate" json:"validate,omitempty"`
}

func (m *MessageQueryValidate) Reset()         { *m = MessageQueryValidate{} }
func (m *MessageQueryValidate) String() string { return proto.CompactTextString(m) }
func (*MessageQueryValidate) ProtoMessage()    {}
func (*MessageQueryValidate) Descriptor() ([]byte, []int) {
	return fileDescriptorQueryValidate, []int{1}
}

func (m *MessageQueryValidate) GetValidate() []*MessageQueryValidate_QueryValidateEntry {
	if m != nil {
		return m.Validate
	}
	return nil
}

type MessageQueryValidate_QueryValidateEntry struct {
	Name  string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value *QueryValidate `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *MessageQueryValidate_QueryValidateEntry) Reset() {
	*m = MessageQueryValidate_QueryValidateEntry{}
}
func (m *MessageQueryValidate_QueryValidateEntry) String() string { return proto.CompactTextString(m) }
func (*MessageQueryValidate_QueryValidateEntry) ProtoMessage()    {}
func (*MessageQueryValidate_QueryValidateEntry) Descriptor() ([]byte, []int) {
	return fileDescriptorQueryValidate, []int{1, 0}
}

func (m *MessageQueryValidate_QueryValidateEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MessageQueryValidate_QueryValidateEntry) GetValue() *QueryValidate {
	if m != nil {
		return m.Value
	}
	return nil
}

var E_Validate = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*QueryValidate)(nil),
	Field:         52121,
	Name:          "atlas.query.validate",
	Tag:           "bytes,52121,opt,name=validate",
	Filename:      "options/query_validate.proto",
}

var E_Message = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*MessageQueryValidate)(nil),
	Field:         52121,
	Name:          "atlas.query.message",
	Tag:           "bytes,52121,opt,name=message",
	Filename:      "options/query_validate.proto",
}

func init() {
	proto.RegisterType((*QueryValidate)(nil), "atlas.query.QueryValidate")
	proto.RegisterType((*QueryValidate_Filtering)(nil), "atlas.query.QueryValidate.Filtering")
	proto.RegisterType((*QueryValidate_Sorting)(nil), "atlas.query.QueryValidate.Sorting")
	proto.RegisterType((*QueryValidate_FieldSelection)(nil), "atlas.query.QueryValidate.FieldSelection")
	proto.RegisterType((*MessageQueryValidate)(nil), "atlas.query.MessageQueryValidate")
	proto.RegisterType((*MessageQueryValidate_QueryValidateEntry)(nil), "atlas.query.MessageQueryValidate.QueryValidateEntry")
	proto.RegisterEnum("atlas.query.QueryValidate_FilterOperator", QueryValidate_FilterOperator_name, QueryValidate_FilterOperator_value)
	proto.RegisterEnum("atlas.query.QueryValidate_ValueType", QueryValidate_ValueType_name, QueryValidate_ValueType_value)
	proto.RegisterExtension(E_Validate)
	proto.RegisterExtension(E_Message)
}

func init() { proto.RegisterFile("options/query_validate.proto", fileDescriptorQueryValidate) }

var fileDescriptorQueryValidate = []byte{
	// 630 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xdf, 0x6e, 0xd3, 0x3e,
	0x14, 0xc7, 0x97, 0xfe, 0x4b, 0x73, 0xfa, 0x5b, 0x7f, 0x96, 0xb5, 0x8b, 0xa8, 0x02, 0x11, 0xba,
	0x5d, 0x14, 0xa4, 0xa6, 0xd3, 0xe0, 0x6a, 0x80, 0xd0, 0x36, 0xb2, 0x51, 0xa9, 0xeb, 0x98, 0xd7,
	0x0d, 0x69, 0x12, 0x54, 0x69, 0xe3, 0x86, 0x48, 0x5e, 0x1c, 0x12, 0x77, 0xd0, 0x67, 0xe0, 0x01,
	0x26, 0xde, 0x87, 0x07, 0x43, 0x76, 0x92, 0x6e, 0x61, 0x6c, 0x13, 0x57, 0x76, 0x7a, 0xbe, 0xdf,
	0x4f, 0x8f, 0x8f, 0x7d, 0x0e, 0x3c, 0xe2, 0x91, 0x08, 0x78, 0x98, 0xf4, 0xbe, 0xce, 0x69, 0xbc,
	0x18, 0x5f, 0xba, 0x2c, 0xf0, 0x5c, 0x41, 0xed, 0x28, 0xe6, 0x82, 0xe3, 0x86, 0x2b, 0x98, 0x9b,
	0xd8, 0x2a, 0xd6, 0xb2, 0x7c, 0xce, 0x7d, 0x46, 0x7b, 0x2a, 0x34, 0x99, 0xcf, 0x7a, 0x1e, 0x4d,
	0xa6, 0x71, 0x10, 0x09, 0x1e, 0xa7, 0xf2, 0xf6, 0x55, 0x0d, 0x56, 0x8f, 0xa5, 0xf6, 0x2c, 0xc3,
	0xe0, 0x5d, 0x30, 0x66, 0x01, 0x13, 0x34, 0x0e, 0x42, 0xdf, 0xd4, 0x2c, 0xad, 0xd3, 0xd8, 0xda,
	0xb0, 0x6f, 0x40, 0xed, 0x82, 0xdc, 0xde, 0xcf, 0xb5, 0xe4, 0xda, 0x86, 0x5f, 0x83, 0x9e, 0xf0,
	0x58, 0x48, 0x42, 0x49, 0x11, 0xda, 0xf7, 0x10, 0x4e, 0x52, 0x25, 0xc9, 0x2d, 0x98, 0xc0, 0xff,
	0xb3, 0x80, 0x32, 0x6f, 0x9c, 0x50, 0x46, 0xa7, 0xf2, 0xac, 0x66, 0x59, 0x51, 0x9e, 0xdd, 0x9b,
	0x07, 0x65, 0xde, 0x49, 0x6e, 0x20, 0xcd, 0x59, 0xe1, 0x1b, 0xef, 0x01, 0x5c, 0xba, 0x6c, 0x4e,
	0xc7, 0x62, 0x11, 0x51, 0xb3, 0x62, 0x69, 0x9d, 0xe6, 0xbd, 0xc7, 0x3a, 0x93, 0xe2, 0xd1, 0x22,
	0xa2, 0xc4, 0xb8, 0xcc, 0xb7, 0x78, 0x03, 0x9a, 0xd7, 0x90, 0xf1, 0x3c, 0x66, 0x66, 0xd5, 0xd2,
	0x3a, 0x06, 0xf9, 0x6f, 0x29, 0x39, 0x8d, 0x19, 0xde, 0x84, 0x35, 0x1a, 0xba, 0x13, 0x46, 0xc7,
	0x21, 0x4d, 0x04, 0xf5, 0xc6, 0x2a, 0x95, 0xc4, 0xac, 0x59, 0x5a, 0xa7, 0x4e, 0x70, 0x1a, 0x1b,
	0xaa, 0x90, 0x4a, 0x3a, 0xc1, 0xeb, 0xb0, 0x5a, 0x94, 0xea, 0x56, 0x59, 0x62, 0xc3, 0x1b, 0xa2,
	0xd6, 0x0f, 0x0d, 0x8c, 0x65, 0xb1, 0xf1, 0x5b, 0xa8, 0xba, 0x8c, 0xf1, 0x6f, 0xa6, 0x66, 0x95,
	0x3b, 0xcd, 0x07, 0x2a, 0x23, 0x4d, 0x47, 0x11, 0x8d, 0x5d, 0xc1, 0x63, 0x92, 0xfa, 0xf0, 0x1b,
	0xa8, 0x78, 0x34, 0x5c, 0x98, 0xa5, 0x7f, 0xf5, 0x2b, 0x5b, 0x6b, 0x1d, 0xf4, 0xec, 0xde, 0xb0,
	0x09, 0xba, 0x17, 0x24, 0xf2, 0x50, 0xea, 0xb9, 0xd4, 0x49, 0xfe, 0xd9, 0x7a, 0x0e, 0xcd, 0xe2,
	0xb5, 0xdc, 0xad, 0x6d, 0x7f, 0x92, 0xda, 0x9b, 0x7f, 0x84, 0x6b, 0x50, 0x72, 0x8e, 0xd1, 0x0a,
	0x36, 0xa0, 0x7a, 0xb8, 0x33, 0xda, 0x7b, 0x8f, 0x34, 0xf9, 0xd3, 0xc1, 0x08, 0x95, 0xd4, 0xea,
	0xa0, 0xb2, 0x5c, 0x07, 0x23, 0x54, 0x51, 0xab, 0x83, 0xaa, 0x58, 0x87, 0xf2, 0xce, 0x60, 0x80,
	0x6a, 0x72, 0xd3, 0x77, 0x8e, 0x91, 0x2e, 0x23, 0xfd, 0x21, 0xaa, 0xb7, 0x37, 0xc1, 0x58, 0x5e,
	0x29, 0x6e, 0x80, 0xfe, 0xce, 0xd9, 0xdf, 0x39, 0x1d, 0x8c, 0xd0, 0x0a, 0x06, 0xa8, 0x9d, 0x8c,
	0x48, 0x7f, 0x78, 0x80, 0x34, 0xb9, 0x1f, 0x9e, 0x1e, 0xee, 0x3a, 0x04, 0x95, 0xda, 0xbf, 0x34,
	0x58, 0x3b, 0xa4, 0x49, 0xe2, 0xfa, 0xb4, 0xd8, 0x20, 0x1f, 0xa0, 0x9e, 0xf7, 0x9c, 0xaa, 0x7e,
	0x63, 0xeb, 0x65, 0xa1, 0x7a, 0x7f, 0x33, 0x15, 0x4b, 0xea, 0x84, 0x22, 0x5e, 0x90, 0x25, 0xa5,
	0x75, 0x0e, 0xf8, 0x76, 0x1c, 0x63, 0xa8, 0x84, 0xee, 0x45, 0x5a, 0x28, 0x83, 0xa8, 0x3d, 0xde,
	0x84, 0xaa, 0x7a, 0x6b, 0x59, 0x5b, 0xb5, 0xee, 0xbe, 0x36, 0x92, 0x0a, 0xb7, 0x3f, 0x5e, 0x67,
	0x8b, 0x1f, 0xdb, 0xe9, 0x3c, 0xb0, 0xf3, 0x79, 0x90, 0x76, 0xcd, 0x51, 0x3a, 0x4f, 0xcc, 0x9f,
	0x57, 0xe5, 0x07, 0xa9, 0x4b, 0xd8, 0xf6, 0x67, 0xd0, 0x2f, 0xd2, 0x93, 0xe2, 0x27, 0xb7, 0xb8,
	0x59, 0x0d, 0xfe, 0x24, 0x3f, 0x7d, 0xb0, 0x50, 0x24, 0x87, 0xee, 0xf6, 0xcf, 0x0f, 0xfc, 0x40,
	0x7c, 0x99, 0x4f, 0xec, 0x29, 0xbf, 0xe8, 0x05, 0xe1, 0x8c, 0x4f, 0x18, 0xff, 0xce, 0x23, 0x1a,
	0xa6, 0xe3, 0x6c, 0xda, 0xf5, 0x69, 0xd8, 0x55, 0xbc, 0xae, 0xe2, 0x75, 0xf3, 0xd4, 0x7a, 0xd9,
	0x80, 0x7c, 0x95, 0xad, 0x93, 0x9a, 0x32, 0xbc, 0xf8, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x63,
	0xaa, 0x63, 0x3a, 0x05, 0x00, 0x00,
}
